seeder:
  file: ./seeder/seeder.rb
  disabled: true

parsers:
  - file: ./parsers/listings.rb
    page_type: listings
    disabled: true

  - file: ./parsers/products.rb
    page_type: products
    disabled: true